title: How reed switches work
hero_image: images/banner.png
description: generic-electronics-reed-switches description
theme: redturquoise, violet, yellow
duration: 1
listed: false
ingredient: true
copyedit: false
curriculum: 
interests:
technologies:
site_areas:
steps:
  - title: How reed switches work

